sudo: false
language: node_js
node_js:
  - 12
install:
  - yarn install
before_script:
  - yarn start:test &
  - while ! echo exit | curl --fail --head --silent http://localhost:8006/test; do sleep 1; done
script:
  - yarn test
